name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
        env:
          CI: true

      # Build Backend Users
      - name: Build Backend Users
        run: |
          cd backend/Users
          npm install
          npm run build # Zakładając, że masz skrypt build w package.json
        env:
          CI: true

      # Build Backend CustomerService
      - name: Build Backend CustomerService
        run: |
          cd backend/CustomerService
          npm install
          npm run build # Zakładając, że masz skrypt build w package.json
        env:
          CI: true

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/frontend" # Adjust according to your structure
          api_location: "backend" # This should point to the root of your backend code if you have multiple functions
          output_location: "dist" # The location where Vue build outputs the files

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
